-- MySQL Script generated by MySQL Workbench
-- Mon Apr 11 14:24:25 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema thesis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema thesis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `thesis` DEFAULT CHARACTER SET utf8 ;
USE `thesis` ;

-- -----------------------------------------------------
-- Table `thesis`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thesis`.`user` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nameFirst` VARCHAR(45) NOT NULL,
  `nameLast` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state/region` VARCHAR(45) NOT NULL,
  `zipCode` INT(10) NOT NULL,
  `cell` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thesis`.`facebook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thesis`.`facebook` (
  `idUser` INT(10) NOT NULL,
  `screenName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  CONSTRAINT `idUserFK`
    FOREIGN KEY (`idUser`)
    REFERENCES `thesis`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thesis`.`credentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thesis`.`credentials` (
  `idUser` INT(10) NOT NULL AUTO_INCREMENT,
  `hash` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `thesis`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thesis`.`privateMessages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thesis`.`privateMessages` (
  `idMessage` INT(10) NOT NULL AUTO_INCREMENT,
  `messageType` VARCHAR(20) NULL,
  `idUserSender` INT(10) NOT NULL,
  `idUserReceiver` INT(10) NOT NULL,
  `messageStatus` INT(1) NULL,
  `messages` TEXT(5000) NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`idMessage`),
  INDEX `idUserReceiverFK_idx` (`idUserReceiver` ASC),
  CONSTRAINT `idUserSenderFK`
    FOREIGN KEY (`idUserSender`)
    REFERENCES `thesis`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUserReceiverFK`
    FOREIGN KEY (`idUserReceiver`)
    REFERENCES `thesis`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thesis`.`google`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thesis`.`google` (
  `idUser` INT(10) NOT NULL AUTO_INCREMENT,
  `screenName` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`),
  CONSTRAINT `idUserGoogleFk`
    FOREIGN KEY (`idUser`)
    REFERENCES `thesis`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thesis`.`chatroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thesis`.`chatroom` (
  `idChatroom` INT(10) NOT NULL AUTO_INCREMENT,
  `idChatroomType` INT(10) NOT NULL,
  `locationName` VARCHAR(45) NOT NULL,
  `idSender` INT(10) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`idChatroom`),
  INDEX `idSenderFK_idx` (`idSender` ASC),
  CONSTRAINT `idSenderFK`
    FOREIGN KEY (`idSender`)
    REFERENCES `thesis`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thesis`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thesis`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thesis`.`userChatroomJct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thesis`.`userChatroomJct` (
  `idUser` INT(10) NOT NULL,
  `idChatroom` INT(10) NOT NULL,
  PRIMARY KEY (`idUser`, `idChatroom`),
  INDEX `idChatroomFK_idx` (`idChatroom` ASC),
  CONSTRAINT `idUserFK`
    FOREIGN KEY (`idUser`)
    REFERENCES `thesis`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idChatroomFK`
    FOREIGN KEY (`idChatroom`)
    REFERENCES `thesis`.`chatroom` (`idChatroom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
